tables:
  - name: artists
    role: dim
    columns:
      - name: id
        role: primary_key
        type: FLOAT
        sync: false
      - name: name
        role: dimension
        type: VARCHAR(255)
        sync: true
  - name: albums
    role: dim
    columns:
      - name: id
        role: primary_key
        type: FLOAT
        sync: false
      - name: title
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: artist_id
        role: foreign_key
        type: FLOAT
        sync: true
  - name: employees
    role: dim
    columns:
      - name: id
        role: primary_key
        type: FLOAT
        sync: false
      - name: last_name
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: first_name
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: title
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: reports_to
        role: dimension
        type: FLOAT
        sync: true
      - name: birth_date
        role: dimension
        type: DATETIME
        sync: false
      - name: hire_date
        role: dimension
        type: DATETIME
        sync: true
      - name: address
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: city
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: state
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: country
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: postal_code
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: phone
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: fax
        role: dimension
        type: VARCHAR(255)
        sync: false
      - name: email
        role: dimension
        type: VARCHAR(255)
        sync: true
  - name: customers
    role: dim
    columns:
      - name: id
        role: primary_key
        type: FLOAT
        sync: false
      - name: first_name
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: last_name
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: company
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: address
        role: dimension
        type: VARCHAR(255)
        sync: false
      - name: city
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: state
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: country
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: postal_code
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: phone
        role: dimension
        type: VARCHAR(255)
        sync: false
      - name: fax
        role: dimension
        type: VARCHAR(255)
        sync: false
      - name: email
        role: dimension
        type: VARCHAR(255)
        sync: false
      - name: support_rep_id
        role: foreign_key
        type: FLOAT
        sync: false
  - name: genres
    role: dim
    columns:
      - name: id
        role: primary_key
        type: FLOAT
        sync: false
      - name: name
        role: dimension
        type: VARCHAR(255)
        sync: true
  - name: invoices
    role: fact
    columns:
      - name: id
        role: primary_key
        type: FLOAT
        sync: false
      - name: customer_id
        role: foreign_key
        type: FLOAT
        sync: true
      - name: invoice_date
        role: dimension
        type: DATETIME
        sync: true
      - name: billing_address
        role: dimension
        type: VARCHAR(255)
        sync: false
      - name: billing_city
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: billing_state
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: billing_country
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: billing_postal_code
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: total
        role: measure
        type: FLOAT
        sync: true
  - name: media_types
    role: dim
    columns:
      - name: id
        role: primary_key
        type: FLOAT
        sync: false
      - name: name
        role: dimension
        type: VARCHAR(255)
        sync: true
  - name: tracks
    role: dim
    columns:
      - name: id
        role: primary_key
        type: FLOAT
        sync: false
      - name: name
        role: dimension
        type: VARCHAR(255)
        sync: true
      - name: album_id
        role: foreign_key
        type: FLOAT
        sync: true
      - name: media_type_id
        role: foreign_key
        type: FLOAT
        sync: true
      - name: genre_id
        role: foreign_key
        type: FLOAT
        sync: true
      - name: composer
        role: dimension
        type: VARCHAR(255)
        sync: false
      - name: milliseconds
        role: measure
        type: FLOAT
        sync: false
      - name: bytes
        role: measure
        type: FLOAT
        sync: false
      - name: unit_price
        role: measure
        type: FLOAT
        sync: false
  - name: invoice_lines
    role: fact
    columns:
      - name: id
        role: primary_key
        type: FLOAT
        sync: false
      - name: invoice_id
        role: foreign_key
        type: FLOAT
        sync: false
      - name: track_id
        role: foreign_key
        type: FLOAT
        sync: false
      - name: unit_price
        role: measure
        type: FLOAT
        sync: false
      - name: quantity
        role: measure
        type: FLOAT
        sync: false
  - name: playlists
    role: dim
    columns:
      - name: id
        role: primary_key
        type: FLOAT
        sync: false
      - name: name
        role: dimension
        type: VARCHAR(255)
        sync: true
  - name: playlist_tracks
    role: dim
    columns:
      - name: playlist_id
        role: foreign_key
        type: FLOAT
        sync: false
      - name: track_id
        role: foreign_key
        type: FLOAT
        sync: false
metrics:
  - name: total_revenue
    description: total revenue from all invoices
    relevant_columns:
      - invoices.total
  - name: avg_unit_price
    description: average unit price of tracks
    relevant_columns:
      - tracks.unit_price
